### ISSUE TITLE
bitbucket-header-color: exclude Bitbucket Blog

### ISSUE THREAD

**Issue by dtruebin** [rybak/atlassian-tweaks#17]
By default, the style applies to sites with URL starting with `https://bitbucket`, which is fine in most cases. (Personally, I'd want various corporate Bitbucket instances to be custom-styled, and bitbucket.org's styles to be left intact, but that's just my preference which I can achieve through Stylus extension's _Custom excluded sites_)

But then the Bitbucket Blog at https://bitbucket.org/blog/ happens to be custom-styled as well, which probably doesn't make much sense and should be disabled by default.

![image](https://github.com/user-attachments/assets/514a5c50-c4fa-4dab-9784-909d64683433)

**Comment by rybak** [comment]
Thanks!
